name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  tests-ubuntu:

    runs-on: ubuntu-latest
    
    steps:

    - uses: actions/checkout@v2

    - name: Install Standard
      run: npm i -D standard

    - name: run tests
      run: npm run test

  tests-windows:

    runs-on: windows-latest
    
    steps:

    - uses: actions/checkout@v2

    - name: Install Standard
      run: npm i -D standard

    - name: run tests
      run: npm run test